In [76]:
import numpy as np
import pandas as pd

In [4]:
die1 = np.random.choice([1, 2, 3, 4, 5, 6], size = 10000)
die2 = np.random.choice([1, 2, 3, 4, 5, 6], size = 10000)

In [5]:
doubles = (die1 == die2)

In [6]:
doubles

array([False,  True, False, ..., False, False, False])

In [7]:
# How likely is it that you roll doubles when rolling two dice?
doubles.mean()

0.166

In [14]:
flips = np.random.choice([0, 1], size = (1000000, 8))

In [15]:
flips

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 0, 0]])

In [16]:
totheads = flips.sum(axis = 1)

In [17]:
totheads

array([1, 5, 4, ..., 6, 3, 3])

In [20]:
equals_3_of_8 = (totheads == 3)

In [21]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads?
equals_3_of_8.mean()

0.218114

In [22]:
greater_than_3 = (totheads > 3)

In [23]:
# What is the probability of getting more than 3 heads?
greater_than_3.mean()

0.637193

In [29]:
bills1 = np.random.choice([0, 1], size = (1000000, 2), p = [.75, .25])


In [30]:
bills1

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [1, 0],
       [1, 0],
       [0, 0]])

In [31]:
both_science = (bills1.sum(axis = 1) == 2)

In [33]:
# There are approximately 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that
# the two billboards I drive past both have data science students on them?
both_science.mean()

0.062666

In [34]:
# Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine.

popdata = np.random.normal(3, 1.5, size = (100000, 5))

In [36]:
use_of_week = popdata.sum(axis = 1)

In [39]:
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be 
# able to buy some poptarts on Friday afternoon?

(use_of_week < 17).mean()

0.72427

In [40]:
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.

men = np.random.normal(178, 8, size = (100000))
women = np.random.normal(170, 6, size = (100000))

In [42]:
are_they_though = (women > men)

In [44]:
# If a man and woman are chosen at random, P(woman taller than man)?

are_they_though.mean()

0.21215

In [45]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted
# and the installation fails. 
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students

classes_of_fifty = np.random.choice([0, 1], size = (100000, 50), p = [.996, .004])

In [53]:
# What are the odds that after having 50 students download anaconda, no one has an installation issue?

(classes_of_fifty.sum(axis = 1) < 1).mean()

0.81768

In [54]:
# 100 students?

classes_of_hunned = np.random.choice([0, 1], size = (100000, 100), p = [.996, .004])
(classes_of_hunned.sum(axis = 1) < 1).mean()

0.66891

In [57]:
# What is the probability that we observe an installation issue within the first 
# 150 students that download anaconda?

classes_of_hunned_fitty = np.random.choice([0, 1], size = (100000, 150), p = [.996, .004])
(classes_of_hunned_fitty.sum(axis = 1) > 0).mean()

0.4508

In [59]:
# How likely is it that 450 students all download anaconda without an issue?

classes_of_450 = np.random.choice([0, 1], size = (100000, 450), p = [.996, .004])
(classes_of_450.sum(axis = 1) < 1).mean()

0.16537

In [60]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days.

trucks = np.random.choice([0, 1], size = [100000, 3], p = [.3, .7])
trucks

array([[0, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [0, 1, 0],
       [0, 0, 0]])

In [61]:
# How unlikely is this?

(trucks.sum(axis = 1) < 1).mean()

0.02727

In [62]:
# How likely is it that a food truck will show up sometime this week?
trucks_week = np.random.choice([0, 1], size = [100000, 7], p = [.3, .7])
(trucks_week.sum(axis = 1) > 0).mean()

0.99971

In [93]:
# If 23 people are in the same room, what are the odds that two of them share a birthday?
# What if it's 20 people? 40?

birthdays = np.random.choice([x for x in range(1, 366)], size = [10000, 23])


In [122]:
def is_repeats(r):
    seen = set()
    for i in r:
        if i in seen:
            return True
        seen.add(i)
    return False

In [123]:
alter_list = []
for x in birthdays:
    x = is_repeats(x)
    alter_list.append(x)

In [124]:
# If 23 people are in the same room, what are the odds that two of them share a birthday?

sum(alter_list)/len(alter_list)

0.5065

In [125]:
birthdays_for_20 = np.random.choice([x for x in range(1, 366)], size = [10000, 20])

In [126]:
alter_20_list = []
for x in birthdays_for_20:
    x = is_repeats(x)
    alter_20_list.append(x)

In [127]:
# What if it's 20 people?

sum(alter_20_list)/len(alter_20_list)

0.4221

In [128]:
birthdays_for_40 = np.random.choice([x for x in range(1, 366)], size = [10000, 40])

In [129]:
alter_40_list = []
for x in birthdays_for_40:
    x = is_repeats(x)
    alter_40_list.append(x)

In [130]:
sum(alter_40_list)/len(alter_40_list)

0.8966